server:
  port: 8083
spring:
  application:
    name: activemq-consumer
active-mq:
  broker-url: tcp://localhost:61616
  topic: topic-2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



