server:
  port: 8082
spring:
  application:
    name: activemq-producer
active-mq:
  broker-url: tcp://localhost:61616
  queue: vqi
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



